export const watchlist = {
  dates: {
    maximum: '2024-10-02',
    minimum: '2024-08-21',
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg',
      genre_ids: [16, 10751, 35, 28],
      id: 519182,
      original_language: 'en',
      original_title: 'Despicable Me 4',
      overview:
        'Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.',
      popularity: 2522.457,
      poster_path: '/wWba3TaojhK7NdycRhoQpsG0FaH.jpg',
      release_date: '2024-06-20',
      title: 'Despicable Me 4',
      video: false,
      vote_average: 7.2,
      vote_count: 1791,
    },
    {
      adult: false,
      backdrop_path: '/Asg2UUwipAdE87MxtJy7SQo08XI.jpg',
      genre_ids: [28, 14, 27],
      id: 957452,
      original_language: 'en',
      original_title: 'The Crow',
      overview:
        'Soulmates Eric and Shelly are brutally murdered when the demons of her dark past catch up with them. Given the chance to save his true love by sacrificing himself, Eric sets out to seek merciless revenge on their killers, traversing the worlds of the living and the dead to put the wrong things right.',
      popularity: 1875.773,
      poster_path: '/58QT4cPJ2u2TqWZkterDq9q4yxQ.jpg',
      release_date: '2024-08-21',
      title: 'The Crow',
      video: false,
      vote_average: 5.424,
      vote_count: 445,
    },
    {
      adult: false,
      backdrop_path: '/zAqBIeO71BFL7bAtP5TFzVjVamy.jpg',
      genre_ids: [10749, 18],
      id: 1079091,
      original_language: 'en',
      original_title: 'It Ends with Us',
      overview:
        "When a woman's first love suddenly reenters her life, her relationship with a charming, but abusive neurosurgeon is upended, and she realizes she must learn to rely on her own strength to make an impossible choice for her future.",
      popularity: 1358.296,
      poster_path: '/cSMdFWmajaX4oUMLx7HEDI84GkP.jpg',
      release_date: '2024-08-07',
      title: 'It Ends with Us',
      video: false,
      vote_average: 6.889,
      vote_count: 579,
    },
    {
      adult: false,
      backdrop_path: '/dTaqzXA1auKRUjHPQjR3u0W7Gfl.jpg',
      genre_ids: [9648, 53],
      id: 840705,
      original_language: 'en',
      original_title: 'Blink Twice',
      overview:
        'When tech billionaire Slater King meets cocktail waitress Frida at his fundraising gala, he invites her to join him and his friends on a dream vacation on his private island. But despite the epic setting, beautiful people, ever-flowing champagne, and late-night dance parties, Frida can sense that there’s something sinister hiding beneath the island’s lush façade.',
      popularity: 1017.493,
      poster_path: '/lZGOK0I2DJSRlEPNOAFTSNxSjDD.jpg',
      release_date: '2024-08-21',
      title: 'Blink Twice',
      video: false,
      vote_average: 6.646,
      vote_count: 474,
    },
    {
      adult: false,
      backdrop_path: '/1pbV8uC6EUYOYnPqWfrQFPdAj1O.jpg',
      genre_ids: [80, 28, 12, 53, 18],
      id: 1147710,
      original_language: 'ko',
      original_title: '하이재킹',
      overview:
        'Pilots Tae-in and Gyu-sik are set to fly to Gimpo. Under the guidance of flight attendant Ok-soon, passengers are busy boarding. However, shortly after takeoff, a homemade bomb explodes, turning the cabin into chaos.',
      popularity: 957.046,
      poster_path: '/1ahGkWMv8Cehlf3hwCSlwJdXaej.jpg',
      release_date: '2024-06-21',
      title: 'Hijack 1971',
      video: false,
      vote_average: 6.514,
      vote_count: 35,
    },
    {
      adult: false,
      backdrop_path: '/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg',
      genre_ids: [878, 27],
      id: 933260,
      original_language: 'en',
      original_title: 'The Substance',
      overview:
        'A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.',
      popularity: 1187.363,
      poster_path: '/lqoMzCcZYEFK729d6qzt349fB4o.jpg',
      release_date: '2024-09-07',
      title: 'The Substance',
      video: false,
      vote_average: 7.201,
      vote_count: 172,
    },
    {
      adult: false,
      backdrop_path: '/blqiNjJefmY10Wx6y2vgJJWljJj.jpg',
      genre_ids: [28, 53],
      id: 949484,
      original_language: 'en',
      original_title: 'Hounds of War',
      overview:
        'After a mission goes wrong, only one of a group of mercenaries is left alive to avenge his fallen brothers.',
      popularity: 991.232,
      poster_path: '/lRBT73EWsiQPuqK3YS3BnBW0Zwi.jpg',
      release_date: '2024-08-29',
      title: 'Hounds of War',
      video: false,
      vote_average: 6.446,
      vote_count: 56,
    },
    {
      adult: false,
      backdrop_path: '/A1dZ6faTjg0e6HYftBmEKujuXGQ.jpg',
      genre_ids: [35, 14, 27],
      id: 917496,
      original_language: 'en',
      original_title: 'Beetlejuice Beetlejuice',
      overview:
        "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Betelgeuse, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
      popularity: 918.22,
      poster_path: '/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg',
      release_date: '2024-09-04',
      title: 'Beetlejuice Beetlejuice',
      video: false,
      vote_average: 7.2,
      vote_count: 745,
    },
  ],
  total_pages: 252,
  total_results: 5037,
};
